title: 'Michael Fangman | UX & UI Designer'
author:
  name: 'Michael Fangman'
  email: hello@michaelfangman.com
taxonomies:
  - category
metadata:
  description: ' UX & UI Designer living and working in Mpls'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
